// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsNw68Aw0Psn1vXC_k7PR5b_djHWr666I',
    appId: '1:1073702990942:android:aab40d2cc856dd6f55f0cf',
    messagingSenderId: '1073702990942',
    projectId: 'sewainaja-b4834',
    databaseURL: 'https://sewainaja-b4834-default-rtdb.firebaseio.com',
    storageBucket: 'sewainaja-b4834.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSMvgPE401Jm7pdvjO4uLtiT8U68NmgBo',
    appId: '1:1073702990942:ios:b7a19447cce725bd55f0cf',
    messagingSenderId: '1073702990942',
    projectId: 'sewainaja-b4834',
    databaseURL: 'https://sewainaja-b4834-default-rtdb.firebaseio.com',
    storageBucket: 'sewainaja-b4834.firebasestorage.app',
    iosClientId: '1073702990942-p85k1nnf8a6kac3bp9rjtsodt1tcfvka.apps.googleusercontent.com',
    iosBundleId: 'com.example.sewainaja',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJCr3VkZBlqFTbBF0EfnLheSO5hhP5jdw',
    appId: '1:1073702990942:web:395205356a1af0fe55f0cf',
    messagingSenderId: '1073702990942',
    projectId: 'sewainaja-b4834',
    authDomain: 'sewainaja-b4834.firebaseapp.com',
    databaseURL: 'https://sewainaja-b4834-default-rtdb.firebaseio.com',
    storageBucket: 'sewainaja-b4834.firebasestorage.app',
    measurementId: 'G-L6KK0K5GF9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSMvgPE401Jm7pdvjO4uLtiT8U68NmgBo',
    appId: '1:1073702990942:ios:b7a19447cce725bd55f0cf',
    messagingSenderId: '1073702990942',
    projectId: 'sewainaja-b4834',
    databaseURL: 'https://sewainaja-b4834-default-rtdb.firebaseio.com',
    storageBucket: 'sewainaja-b4834.firebasestorage.app',
    iosClientId: '1073702990942-p85k1nnf8a6kac3bp9rjtsodt1tcfvka.apps.googleusercontent.com',
    iosBundleId: 'com.example.sewainaja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJCr3VkZBlqFTbBF0EfnLheSO5hhP5jdw',
    appId: '1:1073702990942:web:4f21946639a9d98d55f0cf',
    messagingSenderId: '1073702990942',
    projectId: 'sewainaja-b4834',
    authDomain: 'sewainaja-b4834.firebaseapp.com',
    databaseURL: 'https://sewainaja-b4834-default-rtdb.firebaseio.com',
    storageBucket: 'sewainaja-b4834.firebasestorage.app',
    measurementId: 'G-PSQQNY2SN2',
  );

}